version: '3'

services:
  db_mysql:
    image: mysql:8
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql_db
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}